WIP: nrai/agency update requests/cc 15
CodeTheDream/conectate-carolina pull request #104
Opened 2021-06-14 14:03 UTC by nrailsy97

- Created `agency_update_requests` table

2021-06-22 18:19 UTC, nrailsy97 commented
https://user-images.githubusercontent.com/25111094/122978638-ba41d900-d364-11eb-8831-0cb3482037ec.mov

2021-08-09 17:12 UTC, nrailsy97 commented
<img width="863" alt="Screen Shot 2021-08-09 at 1 10 10 PM" src="https://user-images.githubusercontent.com/25111094/128746375-54a789bf-1979-4c0a-8fc6-3d3c31a10b9a.png">

<img width="1395" alt="Screen Shot 2021-08-09 at 1 10 42 PM" src="https://user-images.githubusercontent.com/25111094/128746396-b8180e6d-eb02-4d70-bf99-c032c5ec8a22.png">

2021-08-10 19:33 UTC, micronix requested changes
Just small changes

2021-08-10 19:33 UTC, micronix commented on app/views/agency_update_requests/edit.html.erb
> +            <%= f.hidden_field :submitter_email, value: @agency_update_request.submitter_email  %>
remove this so that the information is not updatable

2021-08-10 19:33 UTC, micronix commented on db/migrate/20210809144224_add_submitted_by_and_submitter_email_to_agency_update_requests.rb
> +    add_column :agency_update_requests, :submitter_email, :string
add a check so that `null: false`

2021-08-11 17:01 UTC, micronix approved these changes
Looks Good

2021-08-11 17:03 UTC, merged